apiVersion: apps/v1
kind: Deployment
metadata:
  name: select-picture-sequentially
spec:
  selector:
    matchLabels:
      app: select-picture-sequentially
  template:
    metadata:
      labels:
        app: select-picture-sequentially
    spec:
      containers:
      - name: select-picture-sequentially
        imagePullPolicy: IfNotPresent
        image: latonaio/select-picture-sequentially:latest
        command:
          - /bin/sh
          - -c
          - "while :; do sleep 10; done"
        env:
          - name: CONNECTION_MODE
            value: direct
          - name: SELECT_NUM
            value: "3"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - name: data
            mountPath: /var/lib/aion/Data/
          - name: scripts
            mountPath: /var/lib/aion/Runtime/select-picture-sequentially
      volumes:
        - name: data
          hostPath:
            path: /var/lib/aion/Data/
        - name: scripts
          hostPath:
            path: /home/toyota/workspace/select-picture-sequentially